# Generated by Django 5.1 on 2024-08-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0005_propostainvestimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropostaInvestimento',
        ),
    ]
